# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `sprockets-rails` gem.
# Please instead update this file by running `bin/tapioca gem sprockets-rails`.

# source://sprockets-rails//lib/sprockets/rails/version.rb#1
module Sprockets; end

# source://sprockets-rails//lib/sprockets/rails/version.rb#2
module Sprockets::Rails; end

# source://sprockets-rails//lib/sprockets/rails/version.rb#3
Sprockets::Rails::VERSION = T.let(T.unsafe(nil), String)
