# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{js-routes}
  s.version = "0.8.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bogdan Gusiev"]
  s.date = %q{2013-02-13}
  s.description = %q{Generates javascript file that defines all Rails named routes as javascript helpers}
  s.email = %q{agresso@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt"
  ]
  s.files = `git ls-files`.split("\n")
  s.homepage = %q{http://github.com/railsware/js-routes}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.0}
  s.summary = %q{Brings Rails named routes to javascript}

  s.add_runtime_dependency(%q<rails>, [">= 3.2"])
  s.add_development_dependency(%q<therubyracer>, [">= 0"])
  s.add_development_dependency(%q<rspec>, ["~> 2.10.0"])
  s.add_development_dependency(%q<bundler>, [">= 1.1.0"])
  s.add_development_dependency(%q<jeweler>, ["~> 1.6.2"])
  s.add_development_dependency(%q<guard>, [">= 0"])
  s.add_development_dependency(%q<rb-fsevent>, [">= 0"])
  s.add_development_dependency(%q<guard-coffeescript>, [">= 0"])
end

