require "active_support/core_ext/string/strip"
require "fileutils"
require "spec_helper"

describe JsRoutes, "compatibility with UMD" do
  describe "generated js" do
    subject do
      described_class.generate(
        module_type: "UMD",
        include: /book|inboxes|inbox_message/
      )
    end

    it "includes a comment in the header" do
      expect(subject).to include("@file Generated by js-routes #{JsRoutes::VERSION}")
      expect(subject).to include("Based on Rails #{Rails.version} routes of App")
      expect(subject).to include("@see https://github.com/railsware/js-routes")
      expect(subject).to include("@version #{described_class.digest}")
    end

    it "calls route function for each route" do
      expect(subject).to include("inboxes_path: __route(")
    end

    it "has correct function without arguments signature" do
      expect(subject).to include('inboxes_path: __route({"format":{}}')
    end

    it "has correct function with arguments signature" do
      expect(subject).to include('inbox_message_path: __route({"inbox_id":{"r":true},"id":{"r":true},"format":{}}')
    end

    it "has correct function signature with unordered hash" do
      expect(subject).to include('inbox_message_attachment_path: __route({"inbox_id":{"r":true},"message_id":{"r":true},"id":{"r":true}}')
    end

    it "has correct function comment with options argument" do
      expect(subject).to include(<<-DOC.rstrip)
  /**
   * Generates rails route to
   * /inboxes(.:format)
   * @param {object | undefined} options
   * @returns {string} route path
   */
  inboxes_path: __route
      DOC
    end

    it "has correct function comment with arguments" do
      expect(subject).to include(<<-DOC.rstrip)
  /**
   * Generates rails route to
   * /inboxes/:inbox_id/messages/:message_id/attachments/new
   * @param {any} inbox_id
   * @param {any} message_id
   * @param {object | undefined} options
   * @returns {string} route path
   */
  new_inbox_message_attachment_path: __route
      DOC
    end

    it "routes should be sorted in alphabetical order" do
      expect(subject.index("book_path")).to be <= subject.index("inboxes_path")
    end
  end

  describe ".generate!" do
    let(:name) { Rails.root.join("app", "assets", "javascripts", "routes.js") }

    before do
      described_class.remove!(name)
      described_class.generate!(file: name)
    end

    after do
      described_class.remove!(name)
    end

    after(:all) do
      FileUtils.rm_f("#{File.dirname(__FILE__)}/../routes.js") # let(:name) is not available here
    end

    it "does not generate file before initialization" do
      expect(File).not_to exist(name)
    end
  end
end
