name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: 
          - ruby: "2.7"
            gemfile: gemfiles/rails50_sprockets_3.gemfile
          - ruby: "2.7"
            gemfile: gemfiles/rails51_sprockets_3.gemfile
          - ruby: "2.7"
            gemfile: gemfiles/rails52_sprockets_3.gemfile
          - ruby: "3.2"
            gemfile: gemfiles/rails70_sprockets_4.gemfile
          - ruby: "3.3"
            gemfile: gemfiles/rails80_sprockets_4.gemfile
          - ruby: "4.0"
            gemfile: gemfiles/rails81_sprockets_4.gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - uses: actions/setup-node@v6
        with:
          node-version: "20"

      - name: Enable Corepack
        run: corepack enable

      - name: install dependencies
        run: yarn install

      - name: test
        run: bundle exec rake spec
